import type { Metadata } from "next";
import { Rubik as FontSans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/utils/utils";
import { ThemeProvider } from "@/components/themeProvider";
import { ruRU } from "@clerk/localizations";

const fontSans = FontSans({ subsets: ["cyrillic"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Brief App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <ClerkProvider localization={ruRU}>
        <body className={cn("font-sans antialiased", fontSans.className)}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* {modal} */}
            {children}
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
