import type { Metadata } from "next";
import { Rubik as FontSans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "@/utils/utils";
import { ThemeProvider } from "@/app/dashboard/_components/theme-provider";
import { ruRU } from "@clerk/localizations";
import Header from "./dashboard/_components/header";
import { Toaster } from "@/components/ui/sonner";

const fontSans = FontSans({ subsets: ["cyrillic"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Brief App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <ClerkProvider localization={ruRU}>
        <body
          className={cn(
            "font-sans antialiased dark:bg-neutral-950",
            fontSans.className,
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
          >
            {/* {modal} */}
            <Header />
            {children}
            <Toaster />
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
